[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PhylUp"
version = "0.1.0"
description = "A tool for updating phylogenetic datasets"
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name="Martha Kandziora", email="martha.kandziora@yahoo.com" }
]
requires-python = ">=3.8"
dependencies = [
  "numpy>=1.15.4",
  "DendroPy==4.4",
  "pytest",
  "pandas",
  "biopython",
  "Concat @ git+https://github.com/mkandziora/phylogenetic_concatenation.git",
  "ncbiTAXONparser @ git+https://github.com/mkandziora/ncbiTAXONparser.git"
]

[project.scripts]
phylup = "phylup.cli:main"


[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
markers = [
    "slow: marks slow tests",
    "api: tests that hit the API",
]
