name: PhylUp integration

on:
  push:
    branches:
      - main
      - dev

jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - uses: mkandziora/PhylUp
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install flake8 pytest pytest-cov pytest-xdist codecov
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
          run: |
            pytest --cov=PhylUp tests/test_*
      - name: upload coverage
          run: |
            codecov
            curl -s https://codecov.io/bash | bash

